<?php

/**
 * BaseGuaulogEntrada
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mes
 * @property integer $anio
 * @property decimal $mide
 * @property decimal $pesa
 * @property decimal $pc
 * @property integer $foto
 * @property Doctrine_Collection $GuaulogDetalles
 * @property Doctrine_Collection $GuaulogFotos
 * @property GuaulogFoto $GuaulogFoto
 * 
 * @method integer             getMes()             Returns the current record's "mes" value
 * @method integer             getAnio()            Returns the current record's "anio" value
 * @method decimal             getMide()            Returns the current record's "mide" value
 * @method decimal             getPesa()            Returns the current record's "pesa" value
 * @method decimal             getPc()              Returns the current record's "pc" value
 * @method integer             getFoto()            Returns the current record's "foto" value
 * @method Doctrine_Collection getGuaulogDetalles() Returns the current record's "GuaulogDetalles" collection
 * @method Doctrine_Collection getGuaulogFotos()    Returns the current record's "GuaulogFotos" collection
 * @method GuaulogFoto         getGuaulogFoto()     Returns the current record's "GuaulogFoto" value
 * @method GuaulogEntrada      setMes()             Sets the current record's "mes" value
 * @method GuaulogEntrada      setAnio()            Sets the current record's "anio" value
 * @method GuaulogEntrada      setMide()            Sets the current record's "mide" value
 * @method GuaulogEntrada      setPesa()            Sets the current record's "pesa" value
 * @method GuaulogEntrada      setPc()              Sets the current record's "pc" value
 * @method GuaulogEntrada      setFoto()            Sets the current record's "foto" value
 * @method GuaulogEntrada      setGuaulogDetalles() Sets the current record's "GuaulogDetalles" collection
 * @method GuaulogEntrada      setGuaulogFotos()    Sets the current record's "GuaulogFotos" collection
 * @method GuaulogEntrada      setGuaulogFoto()     Sets the current record's "GuaulogFoto" value
 * 
 * @package    guaulog
 * @subpackage model
 * @author     Javier Novoa C.
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGuaulogEntrada extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('guaulog_entrada');
        $this->hasColumn('mes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('anio', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mide', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('pesa', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('pc', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('foto', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));


        $this->index('mesanio', array(
             'fields' => 
             array(
              0 => 'mes',
              1 => 'anio',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GuaulogDetalle as GuaulogDetalles', array(
             'local' => 'id',
             'foreign' => 'entrada_id'));

        $this->hasMany('GuaulogFoto as GuaulogFotos', array(
             'local' => 'id',
             'foreign' => 'entrada_id'));

        $this->hasOne('GuaulogFoto', array(
             'local' => 'foto',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'mes',
              1 => 'anio',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}