<?php

/**
 * BaseGuaulogDetalle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $entrada_id
 * @property string $detalle
 * @property GuaulogEntrada $GuaulogEntrada
 * 
 * @method integer        getId()             Returns the current record's "id" value
 * @method integer        getEntradaId()      Returns the current record's "entrada_id" value
 * @method string         getDetalle()        Returns the current record's "detalle" value
 * @method GuaulogEntrada getGuaulogEntrada() Returns the current record's "GuaulogEntrada" value
 * @method GuaulogDetalle setId()             Sets the current record's "id" value
 * @method GuaulogDetalle setEntradaId()      Sets the current record's "entrada_id" value
 * @method GuaulogDetalle setDetalle()        Sets the current record's "detalle" value
 * @method GuaulogDetalle setGuaulogEntrada() Sets the current record's "GuaulogEntrada" value
 * 
 * @package    guaulog
 * @subpackage model
 * @author     Javier Novoa C.
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGuaulogDetalle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('guaulog_detalle');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('entrada_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('detalle', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('GuaulogEntrada', array(
             'local' => 'entrada_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}