<?php

/**
 * GuaulogEntradaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GuaulogEntradaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GuaulogEntradaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GuaulogEntrada');
    }

    /**
     * Truncates data in table
     */
    public function truncate()
    {
      $q = $this->createQuery('q')
	->delete()
	;
      return $q->execute();
    }

    /**
     * Obtiene una entrada dado mes y año
     *
     * @param string $mes el mes
     * @param string $anio el año
     */
    public function getEntradaByMesAnio($mes, $anio)
    {
      $q = $this->createQuery('e')
	->where('e.mes = ?', $mes)
	->addWhere('e.anio = ?', $anio)
	;

      return $q->fetchOne();
    }

    /**
     * Obtiene los años para los que hay entradas
     */
    public function getAnios()
    {
      $q = $this->createQuery('e')
	->select('e.anio')
	->distinct()
	//	->where('e.anio < ?', 2000)
	->orderBy('e.anio DESC')
	;

      return $q->execute();
    }

    /**
     * Obtiene la primer entrada, de todas las entradas ordenadas por mes/año
     */
    public function getPrimera()
    {
      $q = $this->createQuery('e')
	->orderBy('e.anio ASC, e.mes ASC')
	;

      return $q->fetchOne();
    }

    /**
     * Obtiene la ultima entrada, de todas las entradas ordenadas por mes/año
     */
    public function getUltima()
    {
      $q = $this->createQuery('e')
	//	->where('e.anio < ?', 2000)
	->orderBy('e.anio DESC, e.mes DESC')
	;

      return $q->fetchOne();
    }
}
