<?php

/**
 * GuaulogFotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GuaulogFotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GuaulogFotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GuaulogFoto');
    }

    /**
     * Truncates data in table
     */
    public function truncate()
    {
      $q = $this->createQuery('q')
	->delete()
	;
      return $q->execute();
    }

    /**
     * Query para obtener las fotos para una entrada determinada
     *
     * @param string $mes mes
     * @param string $anio año
     */
    public function queryFotosForEntrada($mes, $anio)
    {
      $q = $this->createQuery('f')
	->leftJoin('f.GuaulogEntrada e')
	->where('e.mes = ?', $mes)
	->addWhere('e.anio = ?', $anio)
	;

      return $q;
    }

    /**
     * Obtiene las fotos para una entrada determinada
     *
     * @param string $mes mes
     * @param string $anio año
     */
    public function getFotosForEntrada($mes, $anio)
    {
      $q = $this->queryFotosForEntrada($mes, $anio);
      return $q->execute();
    }

    /**
     * Cleans up foto files not referenced in DB
     */
    public function deleteUnreferencedFotoFiles()
    {
      $fotos = $this->createQuery('f')->execute();

      $fotos_ar = array();
      foreach ($fotos as $foto):
        $fotos_ar[] = $foto->getFoto();
      endforeach;

      GuaulogUtil::backupFotoFiles(sfConfig::get('sf_test_dir').'/fixtures/files/backup');

      if ($handle = opendir(sfConfig::get('sf_upload_dir') . '/fotos')):
	while (false !== ($file = readdir($handle))):
	  if (!is_dir($file) && !in_array($file, $fotos_ar)):
	    GuaulogUtil::deleteFotoFiles($file);
          endif;
        endwhile;
      endif;
    }
}
