<?php

/**
 * GuaulogEntrada
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    guaulog
 * @subpackage model
 * @author     Javier Novoa C.
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GuaulogEntrada extends BaseGuaulogEntrada
{
  /**
   * Obtiene el nombre del mes relacionado con el mes de la entrada
   */
  public function getNombreMes()
  {
    return GuaulogUtil::$meses[$this->getMes()];
  }

  /**
   * Antes de borrar entrada y detalles/fotos, borrar archivos fisicos de fotos en disco
   */
  public function preDelete($event)
  {
    foreach ($this->getGuaulogFotos() as $foto):
      $foto->deleteFotoFiles();
    endforeach;
  }

  public function queryAnterior()
  {
    return Doctrine_Query::create()
      ->from('GuaulogEntrada e')
      ->where('e.anio < ? OR (e.anio = ? AND e.mes < ?)', array($this->getAnio(), $this->getAnio(), $this->getMes()))
      ->orderBy('e.anio DESC, e.mes DESC')
      ;
  }

  public function querySiguiente()
  {
    return Doctrine_Query::create()
      ->from('GuaulogEntrada e')
      ->where('e.anio > ? OR (e.anio = ? AND e.mes > ?)', array($this->getAnio(), $this->getAnio(), $this->getMes()))
      ->orderBy('e.anio ASC, e.mes ASC')
      ;
  }

  /**
   * Dice si existe una entrada anterior de acuerdo a mes/año en la BD
   */
  public function hasAnterior()
  {
    return $this->queryAnterior()->fetchOne() ? true : false;
  }

  /**
   * Dice si existe una entrada siguiente de acuerdo a mes/año en la BD
   */
  public function hasSiguiente()
  {
    return $this->querySiguiente()->fetchOne() ? true : false;
  }

  /**
   * Obtiene la entrada anterior de acuerdo a mes/año en la BD
   */
  public function getAnterior()
  {
    return $this->queryAnterior()->fetchOne();
  }

  /**
   * Obtiene la entrada siguiente de acuerdo a mes/año en la BD
   */
  public function getSiguiente()
  {
    return $this->querySiguiente()->fetchOne();
  }

  /**
   * Quita la relacion entre la entrada y su foto por default
   */
  public function quitaFoto()
  {
    $foto = $this->getGuaulogFoto();

    $this->setGuaulogFoto(null);
    $this->save();

    return $foto;
  }

  /**
   * Establece una foto como foto por default en la relación entrada-foto
   */
  public function updateSetFoto(GuaulogFoto $foto)
  {
    $this->setGuaulogFoto($foto);
    $this->save();
  }
}
