1;2801;0c# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  limite_anios:     10
  use_buttons:      true
  portada_fname:    guaulog
  portada_fext:     jpg
  portada_thmb_ext: jpg
  nombre:
#  nombre:           Guau! Baby Log
  logo:             guaulog.gif
  minilogo:         guaulog_mini.gif
  aboutlogo:        guaulog_mini2.gif
  background:       guaulog_background.png

dev:
  use_buttons:      true

test:
  use_buttons:      false
