# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

foto:
  class:            sfDoctrineRouteCollection
  options:
    model:          GuaulogFoto
    module:         fotos
  prefix_path:      /foto

detalle:
  class:            sfDoctrineRouteCollection
  options:
    model:          GuaulogDetalle
    module:         detalles
    prefix_path:    /detalle

entrada:
  class:            sfDoctrineRouteCollection
  options:
    model:          GuaulogEntrada
    actions:
      [ list, new, create, edit, update, delete ]
    module:         entrada
    prefix_path:    /entrada
    column:         slug
    with_show:      false
    model_methods:
      { object: getEntradaBySlug }

entrada_index:
  url:                /entrada/index.:sf_format
  param:              { module: entrada, action: index, sf_format: html }

entrada_show:
  url:                /entrada/:slug.:sf_format
  class:              sfDoctrineRoute
  options:
    model:            GuaulogEntrada
    type:             object
    method:           getEntradaBySlug
  param:              { module: entrada, action: show, sf_format: html }

homepage:
  url:   /
  param: { module: entrada, action: index }
