all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=guaulog'
      username: guaulog
      password: guaulog_user
      attributes: { default_table_charset: utf8, default_table_collate: utf8_general_ci }
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=guaulog_test'
      username: guaulog
      password: guaulog_user
      attributes: { default_table_charset: utf8, default_table_collate: utf8_general_ci }
